# 以下配置兼容环境变量设置,配置文件优先级高于环境变量
# PROXY: "" # 代理地址 默认值 "",支持http https socks5
# REFRESHCOOKIE: "" # 刷新cookie,目前版本不再推荐使用,建议直接从getsession接口写入账号信息 默认值 ""
# OAUTH_URL: https://xxxxx.xxx.com/ouath # oauth地址 用于集成第三方登录 默认值 ""
# LOGIN_CALLBACK: "/login" # 登录回调地址,用于指定自己的登录页面 默认值 "/login"
# ASSET_PREFIX: https://oaistatic-cdn.closeai.biz # 静态资源前缀,用于指定自己的静态资源地址 默认值 https://oaistatic-cdn.closeai.biz
# ARKOSE_URL: https://tcr9i.closeai.biz/v2/ # arkose地址,用于指定自己的arkose人机验证地址 默认值 https://tcr9i.closeai.biz/v2/
# ADMIN_PASSWORD: xxxxx # 管理员密码 默认值为随机字符串,每次启动都会变化，可以在启动时通过日志查看，也可以指定一个固定值，方便管理
# AUDIT_LIMIT_URL: https://auditlimit.closeai.biz/audit_limit # 审计限制url 默认值 ""

# 以下配置不兼容环境变量设置,只能通过配置文件设置
USERTOKENS: # 用户token,可配置多个,本项内容支持热更新,更改后即时生效
  - "user1"
  - "user2"

# PROXY: "http://127.0.0.1:31280"  # 代理地址
# OAUTH_URL: https://xxxxx.xxx.com/ouath

# 注意注意,以下为新增配置,如需自动创建数据库,必加以下配置
cool:
  autoMigrate: true


# sqlite数据库配置
database:
  default:
    type: "sqlite" # 数据库类型
    name: "./config/cool.sqlite" # 数据库名称,对于sqlite来说就是数据库文件名
    extra: busy_timeout=5000 # 扩展参数 如 busy_timeout=5000&journal_mode=ALL
    createdAt: "create_time" # 创建时间字段名称
    updatedAt: "update_time" # 更新时间字段名称
    # debug: true # 开启调试模式,启用后将在控制台打印相关sql语句

# mysql数据库配置

# database:
#   default: # 数据源名称,当不指定数据源时 default 为默认数据源
#     type: "mysql" # 数据库类型
#     host: "127.0.0.1" # 数据库地址
#     port: "3306" # 数据库端口
#     user: "root" # 数据库用户名
#     pass: "xxxxxxxxx" # 数据库密码
#     name: "cockroachai" # 数据库名称
#     charset: "utf8mb4" # 数据库编码
#     timezone: "Asia/Shanghai" # 数据库时区
#     # debug: true # 是否开启调试模式，开启后会打印SQL日志
#     createdAt: "createTime" # 创建时间字段
#     updatedAt: "updateTime" # 更新时间字段